[build]
  # Build configuration
  command = "npm run build"
  publish = "dist/spa"

  # Environment variables for build
  [build.environment]
    NODE_VERSION = "20"

# Form settings (correct syntax)
[forms.settings]
  spam_protection = true

# Redirects for SPA routing (simplified and working)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers (less restrictive)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
