[build]
  # Simple client build only
  command = "npm run build"
  publish = "dist"

  # Environment variables for build
  [build.environment]
    NODE_VERSION = "20"
    NPM_FLAGS = "--legacy-peer-deps"

[functions]
  # Server functions directory
  directory = "netlify/functions"

# Form settings
[forms]
  # Enable form processing
  settings = true

# Redirects for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
